service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  profile: default
  region: us-east-1
  stage: dev

plugins:
  - serverless-offline

functions:
  api:
    handler: src/api/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  email:
    handler: email.handler
    events:
      - http:
          path: /
          method: post
